// <auto-generated />
using System;
using EscalationAnalysisDb2.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscalationAnalysisDb2.Migrations
{
    [DbContext(typeof(EscalationsDbContext))]
    partial class EscalationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AppUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.CaseOwner", b =>
                {
                    b.Property<int>("CaseOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseOwnerId"));

                    b.Property<string>("CaseOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseOwnerId");

                    b.ToTable("CaseOwners");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.CaseRecord", b =>
                {
                    b.Property<int>("CaseRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseRecordId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("CaseRecordId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CaseNumber");

                    b.HasIndex("CaseOwnerId");

                    b.HasIndex("ReportId");

                    b.HasIndex("SeverityId");

                    b.HasIndex("StatusId");

                    b.ToTable("CaseRecords");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Escalation", b =>
                {
                    b.Property<int>("EscalationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EscalationId"));

                    b.Property<int>("CaseRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EscalationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("EscalationId");

                    b.HasIndex("CaseRecordId");

                    b.HasIndex("EscalationTask");

                    b.HasIndex("SeverityId");

                    b.HasIndex("StatusId");

                    b.ToTable("Escalations");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Severity", b =>
                {
                    b.Property<int>("SeverityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeverityId"));

                    b.Property<string>("SeverityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeverityId");

                    b.ToTable("Severities");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.CaseRecord", b =>
                {
                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.Account", "Account")
                        .WithMany("CaseRecords")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.CaseOwner", "CaseOwner")
                        .WithMany("CaseRecords")
                        .HasForeignKey("CaseOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.Report", "Report")
                        .WithMany("CaseRecords")
                        .HasForeignKey("ReportId");

                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.Severity", "Severity")
                        .WithMany("CaseRecords")
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.Status", "Status")
                        .WithMany("CaseRecords")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("CaseOwner");

                    b.Navigation("Report");

                    b.Navigation("Severity");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Escalation", b =>
                {
                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.CaseRecord", "CaseRecord")
                        .WithMany("Escalations")
                        .HasForeignKey("CaseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.Severity", "Severity")
                        .WithMany()
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaseRecord");

                    b.Navigation("Severity");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Report", b =>
                {
                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.AppUser", null)
                        .WithMany("ExportedReports")
                        .HasForeignKey("AppUserId");

                    b.HasOne("EscalationAnalysisDb2.Domain.Entities.AppUser", "UploadedByUser")
                        .WithMany("UploadedReports")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Account", b =>
                {
                    b.Navigation("CaseRecords");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("ExportedReports");

                    b.Navigation("UploadedReports");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.CaseOwner", b =>
                {
                    b.Navigation("CaseRecords");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.CaseRecord", b =>
                {
                    b.Navigation("Escalations");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Report", b =>
                {
                    b.Navigation("CaseRecords");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Severity", b =>
                {
                    b.Navigation("CaseRecords");
                });

            modelBuilder.Entity("EscalationAnalysisDb2.Domain.Entities.Status", b =>
                {
                    b.Navigation("CaseRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
